<?php

namespace MagicT\PadelUserBundle\Entity;

use MagicT\PadelUserBundle\Entity\PadelUser;
use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PadelUserRepository extends EntityRepository
{
	public function findAllActieveLeden() {
		$qb = $this->getEntityManager()->createQueryBuilder();
		$query = $qb->select('u')
            ->from('PadelUserBundle:PadelUser', 'u')
            ->where('u.lidtot >= :vandaag')
            ->setParameter('vandaag',date('Y-m-d'))
            ->getQuery()
            ->getResult();
        return $query;
	}

	public function findOneRandom() {


        $qb = $this->getEntityManager()->createQueryBuilder();

        $count = $this->createQueryBuilder('u')
             ->select('COUNT(u)')
             ->where('u.lidtot >= :vandaag')
             ->setParameter('vandaag',date('Y-m-d'))
             ->getQuery()
             ->getSingleScalarResult();
             

        $query = $this->createQueryBuilder('u')
            ->setFirstResult(rand(0, $count - 1))
            ->setMaxResults(1)
            ->where('u.lidtot >= :vandaag')
            ->setParameter('vandaag',date('Y-m-d'))
            ->getQuery()
            ->getOneOrNullResult();
            
        return $query;
    }

    public function magReserveren(PadelUser $padeluser)
    {

        
        $maxaantal = $padeluser->getMaxaantalreservaties();
        if($maxaantal==0){
            return true;
        }else{
            $antwoord = $this->getEntityManager()->getRepository('PadelReservatieBundle:Reservatie')->findAantalVoorUser($padeluser,new \DateTime());
            if($antwoord<$maxaantal){
                return true;
            }else{
                return false;
            }
        }
    }
}
