sonata_block:
    default_contexts: [cms]
    blocks:
        # Enable the SonataAdminBundle block
        sonata.admin.block.admin_list:
            contexts:   [admin]
        # Your other blocks
        # 
sonata_user:
    security_acl: true
    manager_type: orm # can be orm or mongodb

sonata_block:
    blocks:
        #...
        sonata.user.block.menu:    # used to display the menu in profile pages
        sonata.user.block.account: # used to display menu option (login option)

fos_user:
    db_driver:      orm # can be orm or odm
    firewall_name:  main
    user_class:     MagicT\PadelUserBundle\Entity\PadelUser


    group:
        group_class:   MagicT\PadelUserBundle\Entity\PadelGroup
        group_manager: sonata.user.orm.group_manager                    # If you're using doctrine orm (use sonata.user.mongodb.user_manager for mongodb)

    service:
        user_manager: sonata.user.orm.user_manager                      # If you're using doctrine orm (use sonata.user.mongodb.group_manager for mongodb)

sonata_user:
    class:
        user:               MagicT\PadelUserBundle\Entity\PadelUser
        # To also override the Group object
        # group:              MagicT\PadelUserBundle\Entity\PadelGroup