fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

sonata_user:
    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
    prefix: /admin

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

padelsite:
    resource: "@PadelSiteBundle/Controller"

padeluser:
    resource: "@PadelUserBundle/Controller"
    type: annotation

padelreservatie:
    resource: "@PadelReservatieBundle/Controller/"
    type:     annotation
    prefix:   /reservatie

settings:
    resource: "@DmishhSettingsBundle/Resources/config/routing.yml"
    prefix: /settings

rest : 
  type : rest 
  resource : "routing_rest.yml"
  prefix : /api

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

fos_login_js:
    pattern: /login
    defaults: { _controller: FOS\UserBundle\Controller\SecurityController::login }
    options:
        expose: true