<?php

namespace MagicT\PadelReservatieBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TypeVeldRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeVeldRepository extends EntityRepository
{
}
