<?php

namespace MagicT\PadelReservatieBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * VeldRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VeldRepository extends EntityRepository
{
	public function findOneRandom() {


        $qb = $this->getEntityManager()->createQueryBuilder();

        $count = $this->createQueryBuilder('u')
             ->select('COUNT(u)')
             ->getQuery()
             ->getSingleScalarResult();
             

        $query = $this->createQueryBuilder('u')
            ->setFirstResult(rand(0, $count - 1))
            ->setMaxResults(1)
            ->getQuery()
            ->getOneOrNullResult();
            
        return $query;
    }
}
