<?php

namespace MagicT\PadelReservatieBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * VeldRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VeldRepository extends EntityRepository
{
	
}
